### PR TITLE
Week 2 bandit labs

### PR DESCRIPTION
**Pull request by srebreni3**
Firstly I created new branch "week-2-bandit-labs",
Then, I solved 10 levels from https://overthewire.org/wargames/, 
I took screenshots and explanations for all commands, 
I put everything in the file "bash-notes.md".

### CODE REVIEW

**Review by borisbradic — CHANGES_REQUESTED** [review]
You are missing "bandit10".

**Review by srebreni3 — COMMENTED** [review]
Thank you

**Comment by srebreni3** [comment]
> You are missing "bandit10".

I did it

**Review by borisbradic — APPROVED** [review]
Now's all good!

**Pull request merged**
